### ISSUE TITLE
TEIID31202 Detected that an already sorted set of values was not in the expected order

### ISSUE THREAD

**Issue by tirupathiraop** [teiid/teiid#1117]
We have a query which in running in our production environment. Its an existing query which was working fine for years till yesterday. Getting below error.

Unable to get next record from result set. at net.sf.jasperreports.engine.JRResultSetDataSource.next(JRResultSetDataSource.java:170) at com.jaspersoft.jasperserver.api.engine.jasperreports.util.JRTimezoneResultSetDataSource.next(JRTimezoneResultSetDataSource.java:50) ... 18 more Caused by: org.teiid.jdbc.TeiidSQLException: TEIID31202 Detected that an already sorted set of values was not in the expected order (typically UTF-16 / UCS-2).

Did some google but didn't find/understand anything.
Referred link: https://issues.jboss.org/browse/TEIID-5339

could someone please help me with this?

**Comment by rareddy** [comment]
What is the type of source? Did you guys upgrade a database underneath recently? The exception is saying that the results from database are to be in certain sort order based on db's sort capability, but returned results do not reflect that.

**Comment by shawkins** [comment]
The details of what Teiid version, source query, and source will matter.  What collations are on the sort columns?  

Since Teiid does not yet have a way to push the sort collation there are settings on the translator to that will disable pushing string sorts.

**Comment by shawkins** [comment]
Marking as closed since there have been no updates.
