### ISSUE TITLE
TEIID-5615 binding NULL in a prepared statement with PDO PostgreSQL client (ODBC)

### ISSUE THREAD

**Issue by gushakov** [teiid/teiid#1130]
Hi,

I've created a JIRA issue

[TEIID-5615](https://issues.jboss.org/browse/TEIID-5615)

Dealing with a problem of using `bindValue` and `bindParam` with a prepared statement when binding NULL to an optional field.

```php
$dbh = new PDO('pgsql:host=<teiid_host>;port=35432;dbname=<vdb_name>;user=<teiid_user>;password=<teiid_password>');
$stmt = $dbh->prepare("INSERT INTO foobar (id, optional) VALUES(?, ?)");
$stmt->bindValue(1, 1);
$stmt->bindValue(2, null, PDO::PARAM_NULL);
$stmt->execute();
```

Here is the exact line which causes the error in our case:

[PgFrontendProtocol.java#L266](https://github.com/teiid/teiid/blob/teiid-parent-11.0.0/runtime/src/main/java/org/teiid/transport/PgFrontendProtocol.java#L266)

the `paramLen` is -1 at this point and this causes the exception.

>Caused by: java.lang.NegativeArraySizeException
        at org.teiid.transport.PgFrontendProtocol.createByteArray(PgFrontendProtocol.java:328)
        at org.teiid.transport.PgFrontendProtocol.buildBind(PgFrontendProtocol.java:266)
        at org.teiid.transport.PgFrontendProtocol.createRequestMessage(PgFrontendProtocol.java:153)
        at org.teiid.transport.PgFrontendProtocol.decode(PgFrontendProtocol.java:133)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        ... 15 more

As far as I can see this is still a problem in all later versions (I did not test it, just by looking at the code).

This type of binding is done normally by Doctrine - popular ORM framework in PHP, so this issue should affect quite a few projects using PHP (pdo_pgsql), Teiid, Postgres setup.

Thank you,

George

**Comment by shawkins** [comment]
Thanks for raising this.  JIRA is our primary issue tracker, so it's fine to just log things there.  This has been addressed in latest and I'll pull it back to 11.2.2 and 12.0.1.
