### ISSUE TITLE
IMPORT FOREIGN SCHEMA LIMIT TO

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1212]
Hi
I'm trying to limit the import to few specific tables but the parser doesn't seem to recognise the LIMIT TO clause. So i did some research in the code "engine/src/main/javacc/org/teiid/query/parser/SQLParser.jj" and i can see the LIMIT TO has been commented out as shown below. Is this feature deprecated OR am i missing something here? Please advise how to achieve what i want to do. Thanks

<IMPORT> [<FOREIGN> <SCHEMA> 
    foreignSchemaName = id(null)]
    //[(<LIMIT> <TO> <LPAREN> identifierList(includeTables) <RPAREN>) | (<EXCEPT> <LPAREN> identifierList(excludeTables) <RPAREN>)]
    <FROM> (<SERVER>{serverType = "native";}|<REPOSITORY>) serverName = id(null)    
    <INTO> schemaName = id(null)

My definition in DDL VDB as an example

IMPORT FOREIGN SCHEMA MIDM LIMIT TO (WH_BOOKS_D) FROM SERVER ora INTO test

**Comment by shawkins** [comment]
Include / exclude is not generally supported by all translators, so it wasn't yet added as a general option on the import statement.  You can instead you import properties to refine what you are importing:

IMPORT FOREIGN SCHEMA MIDM FROM SERVER ora INTO test OPTIONS ("importer.schemaName" 'x', "importer.tableNamePattern" 'WH_BOOKS_D');

See the import properties: http://teiid.github.io/teiid-documents/master/content/reference/JDBC_Translators.html
