### ISSUE TITLE
Example WS SOAP

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1215]
Please kindly point me to an example of how to create  a SOAP ws data source, create a ddl vdb calling  a SOAP ws. 

Much appreciated

Thanks

**Comment by shawkins** [comment]
General docs on a web service data source: http://teiid.github.io/teiid-documents/master/content/admin/Web_Service_Data_Sources.html

An example from our integration tests is: https://github.com/teiid/teiid/blob/06b9828a3fd6dafa358ff93f0a4803e69a3bfdf4/wildfly/test-integration/common/src/test/java/org/teiid/arquillian/IntegrationTestSOAPWebService.java

Which uses the vdb: https://github.com/teiid/teiid/blob/06b9828a3fd6dafa358ff93f0a4803e69a3bfdf4/wildfly/test-integration/common/src/test/resources/soapsvc-vdb.xml

It's in xml, but the ddl for defining procedures for calling / processing results could be similar.

**Comment by yapnel** [comment]
Thanks for the links. 

I have defined the resource adapter and WSDL for WS in the standalone-teiid.xml file and VDB DDL
as per below. The VDB failed to deploy with error "TEIID31070 Empty model;There are no tables, procedures or functions defined in this model test". I was expecting the virtual procedures to be created automatically in the test schema for the corresponding operations defined in the WSDL. Also i was expecting the default invoke and invokeHTTP procs made available too.  

Could you kindly please advise what i may have done incorrectly? THanks 


DDL VDB:
CREATE DATABASE obi VERSION '1.0.0';
USE DATABASE obi VERSION '1.0.0';

CREATE SERVER obi
    VERSION 'one' FOREIGN DATA WRAPPER ws
    OPTIONS (
        "jndi-name" 'java:/wsDS'
    );

CREATE SCHEMA test SERVER obi;



Resource Adapter:
`<resource-adapter id="webservice">
                    <module slot="main" id="org.jboss.teiid.resource-adapter.webservice"/>
                    <transaction-support>NoTransaction</transaction-support>
                    <connection-definitions>
                        <connection-definition class-name="org.teiid.resource.adapter.ws.WSManagedConnectionFactory" jndi-name="java:/wsDS" enabled="true" use-java-context="true" pool-name="teiid-ws-ds">
                            <config-property name="SecurityType">
                                HTTPBasic
                            </config-property>
                            <config-property name="AuthUserName">
                                XXX
                            </config-property>
                            <config-property name="ServiceName">
                                OBIWS
                            </config-property>
                            <config-property name="EndPointName">
                                OBIEndPoint
                            </config-property>
                            <config-property name="NamespaceUri">
                                https://YYY/analytics-ws/saw.dll
                            </config-property>
                            <config-property name="AuthPassword">
                                XXX
                            </config-property>
                            <config-property name="EndPoint">
                                https://YYY/analytics-ws/saw.dll
                            </config-property>
                            <config-property name="Wsdl">
                                https://YYY/analytics-ws/saw.dll/wsdl/v12
                            </config-property>
                        </connection-definition>
                    </connection-definitions>
                </resource-adapter>`

**Comment by shawkins** [comment]
>  I was expecting the virtual procedures to be created automatically in the test schema for the corresponding operations defined in the WSDL.

In an xml vdb the default is to import the metadata from a translator.  When using ddl you need to explicitly use an import:

CREATE SCHEMA test SERVER obi;
IMPORT FROM SERVER obi INTO test;

This makes things more compatible with SQL-MED.

**Comment by yapnel** [comment]
Thank you that has resolve my error.

However, i'm facing this issue using XMLTable to convert the SOAP response back to Tabular format.
I'm trying to pull out the value of this element sawsoap:sessionID. Could you kindly please assist me with the XMLTABLE syntax.?

Thanks

`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:sawsoap="urn://oracle.bi.webservices/v12">
   <soap:Body>
      <sawsoap:logonResult>
         <sawsoap:sessionID xsi:type="xsd:string">41eo696bsgqlte2b3qt234jn2rl1pupbud1gv4isfqgupch3</sawsoap:sessionID>
      </sawsoap:logonResult>
   </soap:Body>
</soap:Envelope>`

**Comment by yapnel** [comment]
I have tried something like below but throwing error. Any advise is much appreciated. 

TEIID30492 Remote org.teiid.api.exception.query.QueryValidatorException: TEIID30492 XMLPARSE expects a STRING, CLOB, VARBINARY, or BLOB value.




`
select x.* from 
(execute test.invoke(binding=>'SOAP12',
                     action=>'MESSAGE',
                     request=>XMLPARSE(DOCUMENT '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:sawsoap="urn://oracle.bi.webservices/v12"><soap:Body><sawsoap:logonResult><sawsoap:sessionID xsi:type="xsd:string">41eo696bsgqlte2b3qt234jn2rl1pupbud1gv4isfqgupch3</sawsoap:sessionID></sawsoap:logonResult></soap:Body></soap:Envelope>' WELLFORMED),
                     endpoint=>'https://XXXXX/analytics-ws/saw.dll?SoapImpl=nQSessionService',
                     stream=>'false')) as f,
XMLTABLE
(
   XMLNAMESPACES( 'http://schemas.xmlsoap.org/soap/envelope' as soap,'urn://oracle.bi.webservices/v12' as sawsoap),
   '/soap:Envelope/soap:Body/sawsoap:logonResult' PASSING XMLPARSE(DOCUMENT f.result) COLUMNS
   sessionid string PATH 'sawsoap:sessionID/text()'
) as x   
;
`
