### ISSUE TITLE
Execute Anonymous Block

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1218]
Is it possible to execute an anonymous block of code against Teiid from SquirrelSQL? An example 

BEGIN
	DECLARE string sessionid = null;
        sessionid = select sessionid from (exec frc.getSession('XXXX','YYYY')) as X;
END;

The reason asking, it will be useful when developing procedures in Teiid with the ability to execute the code directly against it for development and testing. Similarly to developing stored procedure in PL/SQL with anonymous code before wrapping it into an actual stored procedure.

Thanks

**Comment by shawkins** [comment]
> Is it possible to execute an anonymous block of code against Teiid from SquirrelSQL?

There is nothing that will stop you from the Teiid side as anonymous blocks are supported.  Some tools though attempt to parse individual statements when they see delimiters or other procedural constructs.

**Comment by yapnel** [comment]
Which tool do you recommend for executing anonymous block? I have tried SQuirrelSQL and SQLWorkbench and neither work. Kindly please advise

Thanks

**Comment by shawkins** [comment]
They can work, but have issues handling characters such as ; and {} - you'll need to find an option to simply execute the raw sql.
