### ISSUE TITLE
Elytron

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1220]
Is the latest Teiid using Elytron security framework i.e. authorisation and authentication?

Just confused to which method is used for setting up LDAP authentication. Please advise

Thanks

**Comment by shawkins** [comment]
There is an open jira for updating the security config to elytron: https://issues.redhat.com/browse/TEIID-5762

**Comment by yapnel** [comment]
May i please confirm the latest Wildfly management console is using Elytron and Teiid is still using the old security model from picketbox?

**Comment by shawkins** [comment]
That is correct.
