### ISSUE TITLE
Salesforce Object Import

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1228]
Hi

I have managed to connect to Salesforce using the 41 translator and RA. Is there a way to automatically import all the salesforce objects dynamically into the VDB?

THanks

**Comment by shawkins** [comment]
Did you use an import statement?

**Comment by yapnel** [comment]
Hi

With Salesforce, i dont really know what is the foreign schema to use to substitute the public in the statement below. Furthermore, does the importer.tableTypes apply for Salesforce too? Please advise

Thanks

IMPORT FOREIGN SCHEMA public FROM SERVER sf INTO test
    OPTIONS(
        importer.tableTypes 'TABLE'
);

**Comment by shawkins** [comment]
The foreign schema only matters to some of the translators.  With the latest versions of teiid, you can omit the clause:

IMPORT FROM SERVER sf ...

Table types does not apply.  See all the import properties: http://teiid.github.io/teiid-documents/master/content/reference/Salesforce_Translators.html

**Comment by yapnel** [comment]
Thanks. I'm using the below and getting the follow error.


IMPORT FROM SERVER sf INTO Salesforce_Source;


17:54:31,984 ERROR [org.teiid.RUNTIME] (Worker5)  TEIID30021 Uncaught exception processing work: org.teiid.metadata.ParseException: TEIID31259 In the
statement ending with token Salesforce_Source on line 12 column 28 the ddl is not valid: Unexpected element. Parser was expecting element 'urn:partner
.soap.sforce.com:aiPredictionField' but found 'urn:partner.soap.sforce.com:autoNumber'
        at org.teiid.query.parser.QueryParser.parseDDL(QueryParser.java:532)
        at org.teiid.runtime.AbstractVDBDeployer.processVDBDDL(AbstractVDBDeployer.java:479)
        at org.teiid.runtime.AbstractVDBDeployer.metadataLoaded(AbstractVDBDeployer.java:369)
        at org.teiid.runtime.AbstractVDBDeployer.access$000(AbstractVDBDeployer.java:68)
        at org.teiid.runtime.AbstractVDBDeployer$2.run(AbstractVDBDeployer.java:310)
        at org.teiid.jboss.VDBService$6.run(VDBService.java:379)
        at org.teiid.dqp.internal.process.DQPWorkContext.runInContext(DQPWorkContext.java:281)
        at org.teiid.dqp.internal.process.ThreadReuseExecutor$RunnableWrapper.run(ThreadReuseExecutor.java:124)
        at org.teiid.dqp.internal.process.ThreadReuseExecutor$2.run(ThreadReuseExecutor.java:212)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.teiid.metadata.MetadataException: Unexpected element. Parser was expecting element 'urn:partner.soap.sforce.com:aiPredictionField' but
found 'urn:partner.soap.sforce.com:autoNumber'

**Comment by shawkins** [comment]
That sounds like a salesforce version mismatch.  What translator version are you using and what salesforce api version are you hitting?

**Comment by yapnel** [comment]
I'm using org.jboss.teiid.resource-adapter.salesforce-41

**Comment by shawkins** [comment]
The resource adapter defaults to the https://login.salesforce.com/services/Soap/u/40.0 url - this is due to to the 41 service not yet being available when that translator/resource adapter was added.  This has worked for some time, so it would be surprising if it no longer works.  You could set the resource adapter to use https://login.salesforce.com/services/Soap/u/41.0 or even try later versions - but generally the java api is only compatible with a limited range (or a single) service version.

**Comment by yapnel** [comment]
i have tried specifying the URL property in resource adapter with version 41 or 47. both also failed with similar error.

**Comment by shawkins** [comment]
This has been captured as https://issues.redhat.com/browse/TEIID-5898

**Comment by yapnel** [comment]
Hi 

I can see issue 5898 has been resolved and only available in 13.1. Is there an ETA when 13.1 is made available? THanks

**Comment by shawkins** [comment]
Within the next 2 weeks.

**Comment by yapnel** [comment]
Hi @shawkins 

I have downloaded the latest runtime and rerun my Salesforce VDB for dynamic loading of metadata. The VDB got deployed successfully but when i see the DDL in the console, it is empty.

>CREATE DATABASE sf VERSION '1';
USE DATABASE sf VERSION '1';
CREATE FOREIGN DATA WRAPPER "salesforce-41";
CREATE SERVER salesforce FOREIGN DATA WRAPPER "salesforce-41" OPTIONS ("resource-name" 'java:/sfDS');
CREATE SCHEMA Salesforce_Source SERVER salesforce;
SET SCHEMA Salesforce_Source;
IMPORT FROM SERVER sf INTO Salesforce_Source;

Below are the logs

>10:44:54,702 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3)  WFLYSRV0027: Starting deployment of "sf-vdb.ddl" (runtime-name: "sf-vdb.
ddl")
10:44:54,756 INFO  [org.teiid.RUNTIME.VDBLifeCycleListener] (MSC service thread 1-3)  TEIID40118 VDB sf.1 added to the repository
10:44:54,757 INFO  [org.teiid.RUNTIME] (MSC service thread 1-3)  TEIID50029 VDB sf.1 model "Salesforce_Source" metadata is currently being loaded. Sta
rt Time: 12/03/20 10:44
10:44:54,769 INFO  [org.teiid.RUNTIME] (Worker2_async-teiid-threads2)  TEIID50030 VDB sf.1 model "Salesforce_Source" metadata loaded. End Time: 12/03/
20 10:44
10:44:54,932 INFO  [org.jboss.as.server] (External Management Request Threads -- 1)  WFLYSRV0010: Deployed "sf-vdb.ddl" (runtime-name : "sf-vdb.ddl")
10:45:03,459 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:03,475 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:03,475 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:03,490 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:03,490 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:05,576 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:05,576 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:05,576 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:08,790 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:08,806 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:08,806 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:08,806 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:12,265 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:12,265 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:12,265 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:12,265 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:12,265 WARN  [org.teiid.CONNECTOR] (Worker2_async-teiid-threads2)  TEIID13001 Unknown type returned by SalesForce: complexvalue
10:45:12,281 INFO  [org.teiid.RUNTIME.VDBLifeCycleListener] (Worker2_async-teiid-threads2)  TEIID40003 VDB sf.1 is set to ACTIVE

**Comment by yapnel** [comment]
Looks like the DDL is not displaying in the CONSOLE but when i connect to the VDB via squirrelSQL i can see the tables in the schema. Probably a bug in the CONSOLE then.

**Comment by rareddy** [comment]
we do not display the scheme retrieved in console (log right?), I have to check if it shows up DEBUG mode. As per the warnings we were getting, I believe Teiid was getting some extra metadata which we handled in https://issues.redhat.com/browse/TEIID-5815 so if you set a translator property `importer.includeExtensionMetadata=false` in DDL like 

`CREATE SERVER salesforce FOREIGN DATA WRAPPER "salesforce-41" OPTIONS ("resource-name" 'java:/sfDS', "importer.includeExtensionMetadata" 'false');` 

Those should go away.

**Comment by shawkins** [comment]
> Those should go away.

That property is for the additional metadata we associate with what we import.  The warnings are for sobject types that we don't support - which we could handle better, such as fewer warnings.

**Comment by yapnel** [comment]
I should have made it clearer. It is not showing up in Admin Console -> Runtime -> Teiid -> VDB -> Models tab -> Schema DDL button. It is empty even though SCHEMA is LOADED status

**Comment by shawkins** [comment]
> It is empty even though SCHEMA is LOADED status

My recollection is that it's pulling that from the runtime state, so yes it should be populated.  I recall that someone else had a similar issue a while back with a ddl vdb, but I was unable to reproduce it locally.  Essentially the ui is pulling the ddl from the admin call get-schema.  Can you check the server logs for any errors related to that?  Also you could use the AdminApi to make a similar call using the getSchema method and see what the result is.
