### ISSUE TITLE
UTF-8-BOM

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1229]
Hi

Below is what i have defined for the file translator with encoding set to UTF-8-BOM. However, i'm still struggling to load the file and when i see the "file" CLOB it has ï»¿ in the first row of the file which is also the header. Kindly please advise how to handle this type of issue? 

CREATE SERVER "file"
    FOREIGN DATA WRAPPER file
    OPTIONS(
        "Encoding" 'UTF-8-BOM', "ExceptionIfFileNotFound" false, "jndi-name" 'java:/fileDS'
    );

select b.* from 
(exec getTextFiles('\Extracts\Business Entity.txt')) as x, 
TEXTTABLE( x.file COLUMNS CEN_ENTITY_ID string, CEN_NAME00 string DELIMITER '|' HEADER 1) as b;

**Comment by shawkins** [comment]
CREATE SERVER options only affect the "data source", which here is jndi-name.

The other options need to go on a CREATE FOREIGN DATA WRAPPER statement.  See https://issues.redhat.com/browse/TEIID-5850 for more on clarifications that were made, which are now reflected in the docs.
