### ISSUE TITLE
Delimited Field Exceeds Length

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1230]
Hi

I'm facing this teiid error while loading a delimited file. Is it possible to extend the size to handle longer value for delimited field? This is preventing us to load the extract file generated.

Error: TEIID30178 Text parse error: Delimited line is longer than the expected max of 8,000 on text line 1,806 in file:/C:/Temp/VantageExtracts/Risk%20Evaluation.txt.

Thanks

**Comment by shawkins** [comment]
Text processing or a row is in memory, so there must be some max to prevent an OOM on reading a line.  The only workaround currently is to increase the maxStringLength: http://teiid.github.io/teiid-documents/master/content/admin/System_Properties.html

You can also open a JIRA issue for an enhancement to support disk backed texttable clobs.

**Comment by rareddy** [comment]
shouldn't we be using StackOverflow for questions? Or this another form we feel ok to provide community support?

**Comment by yapnel** [comment]
@shawkins This is resolved the issue. BTW, what does the value stand for? Is it bytes or character?

**Comment by shawkins** [comment]
> shouldn't we be using StackOverflow for questions? Or this another form we feel ok to provide community support?

To rephrase you are asking should we turn off github issues.  I'm indifferent.  I seem to get more consistent notifications from github and the content is indexed either way.

**Comment by shawkins** [comment]
> @shawkins This is resolved the issue. BTW, what does the value stand for? Is it bytes or character?

It's in characters.
