### ISSUE TITLE
REST as Source

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1238]
Hi

I have successfully configured the WS Translator to connect to a REST service. The below code returns a blob. What Teiid function can i use to consume this blob so that i can extract the field out? I know the REST service is returning a JSON. 

`EXEC LEANKIT_Source.invokeHttp
   (
      action=>'GET',
      endpoint=>'https://XXXX.com/io/user/me',
      stream=>'TRUE',
      headers=>'{"Authorization":" Bearer <TOKEN>"}'
   )
`

**Comment by shawkins** [comment]
See http://teiid.github.io/teiid-documents/master/content/reference/JSONTABLE.html or the simpler JSONPATH and JSONQUERY functions: http://teiid.github.io/teiid-documents/master/content/reference/JSON_Functions.html

To convert the blob to a clob use the TO_CHARS function: http://teiid.github.io/teiid-documents/master/content/reference/String_Functions.html

**Comment by yapnel** [comment]
Hi
I'm wondering if the below SQL is going to be efficient since it has to pass the f.result each time for each column? Is there a better way of doing it please? Thanks

`select
  JSONPATHVALUE(to_chars(f.result,'UTF-8',TRUE),'$.username') as username,
  JSONPATHVALUE(to_chars(f.result,'UTF-8',TRUE),'$.firstName') as firstname,
  JSONPATHVALUE(to_chars(f.result,'UTF-8',TRUE),'$.lastName') as lastname,
  JSONPATHVALUE(to_chars(f.result,'UTF-8',TRUE),'$.fullName') as fullname,
  JSONPATHVALUE(to_chars(f.result,'UTF-8',TRUE),'$.emailAddress') as email
from
(
   EXEC LEANKIT_Source.invokeHttp
   (
      action=>'GET',
      endpoint=>'XXX/io/user/me',
      stream=>'FALSE',
      headers=>'{"Authorization":" Bearer <TOKEN>"}'
   )
)
as f`

**Comment by shawkins** [comment]
> Is there a better way of doing it please?

Yes, see the JSONTABLE link above.  You can extract tabular results from a single parsing of the incoming document.

**Comment by dbarasti** [comment]
Hello there, didn't want to open a new issue for my problem since I believe it's similar to @yapnel 's. I have a rest service that returns a json. Specifically:
```
{
"cin": {
    "pi": "SJMI_TzU3L",
    "ty": 4,
    "ct": "20200611T135457",
    "ri": "ByUYnv3yaL",
    "rn": "4-20200611135457397HBzv",
    "lt": "20200611T135457",
    "et": "20220611T135457",
    "st": 3,
    "cs": 15,
    "cr": "S",
    "con": "..."
    }
}
```

I defined the following DLL inside the vdb file:

```
CREATE VIEW SensorRegistryView (
			pi string(4000),
			ty integer,
			ct string(4000),
			ri string(4000),
			rn string(4000),
			lt string(4000),
			et string(4000),
			st integer,
			cs integer,
			cr string(4000),
      			con string(4000)
		) AS
		SELECT A.pi, A.ty, A.ct, A.ri, A.rn, A.lt, A.et, A.st, A.cs, A.cr, A.con FROM
		(EXEC SensorsRegistrySource.invokeHttp(action=>'GET', endpoint=>'http://...')) AS f, 
        JSONTABLE(f.result, '$.cin' COLUMNS pi string, ty integer, ct string, ri string, rn string, lt string, et string, st integer, cs integer, cr string, con string) AS A;  
```
And the vdb deploys on Teiid 16.0 correctly. Now, when I use a client (SQuirreL SQL in my case) to access Teiid, a very simple ```select * from SensorRegistryView``` returns the error:

```
Error: TEIID30070 Remote org.teiid.api.exception.query.QueryPlannerException: TEIID30070 The function 'jsontoarray(f.result, '$.cin', FALSE, '@[''pi'']', '@[''ty'']', '@[''ct'']', '@[''ri'']', '@[''rn'']', '@[''lt'']', '@[''et'']', '@[''st'']', '@[''cs'']', '@[''cr'']', '@[''con'']')' is a valid function form, but the arguments do not match a known type signature and cannot be converted using implicit type conversions.
```
Is there something I am doing wrong while using the JSONTABLE function?

Thanks in advance

**Comment by shawkins** [comment]
I think the problem is that the resolving for JSONTABLE is setting the desired type, but not forcing the resolution to clob, so you are not getting the appropriate exception.

The workaround is to add a conversion of f.result to clob - JSONTABLE(to_chars(f.result, 'UTF-8'), ...

**Comment by dbarasti** [comment]
Thank you, @shawkins, that was indeed one problem, but then I still wasn't able to retrieve the data correctly. In the end, the issue was that the content-encoding of the response from the REST service was gzip, while I was expecting a plain JSON body. Removing the compression made the data appear correctly in the table.
