### ISSUE TITLE
REST Pagination

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1240]
Hi

I have a REST source that has pagination enforced.  Does the WS resource adapter able to handle pagination? If so please give an example of how to pull paginated data.

Thanks

**Comment by shawkins** [comment]
The basic ws translator is just request / response handling, so you'd have to implement the pagination at a higher level.

High level pagination support exists for salesforce and odata though.

**Comment by yapnel** [comment]
Any guidance on how to extend the RA/translator for this purpose?

**Comment by shawkins** [comment]
It would take a new translator.  See the ODataExecutionFactory - it is written to use the same webservice connection as the basic WS translator.  However it adds odata layer concepts including the notion of query, which can be paginated.  

Is your source following some kind of standard?

**Comment by rareddy** [comment]
This has been asked one too many times, I wonder if there is a generic way (through either query/path params or headers) in a configurable way through translator properties?

**Comment by yapnel** [comment]
The Leankit API states the below for the pagination standard.


Many of our list endpoints support paging. The limit parameter controls the number of records returned. The offset parameter controls the number of records to skip before returning results. The response also includes page metadata to indicate how many records there are in total


I agree with rareddy if some sort of generic way that is configurable at the translator level.

**Comment by shawkins** [comment]
> I agree with rareddy if some sort of generic way that is configurable at the translator level.

Each framework / source has a different pagination convention - header properties, parameters, continuation token, etc.  Leankit is different than saleforce, odata, spring web data, etc.  It's best to see if there's a high level translator that would help even more - something that will abstract tables or at least better procedure calls.  While having a highly configurable pagination framework for the ws translator sounds nice, at the end of day you'll still have Teiid procedures that are document in and document out, which is not very use friendly.
