### ISSUE TITLE
SOAP WS Large XML Document

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1243]
I am invoking a SOAP WS and the return XML document is very large. Teiid is failing on the below error. Is there a configuration that can be set to handle extremely large document? I have tried setting stream=> TRUE but made no difference. Any advise please? Thanks

`15:58:05,356 INFO  [org.teiid.PROCESSOR] (Worker7_QueryProcessorQueue31) RkaW+0Udspze TEIID31105 Returing warning to client: TEIID31274 string length
126,810,606 is greater than the maximum 4,000 - it will be truncated to the maximum length.
15:58:05,379 WARN  [org.teiid.PROCESSOR] (Worker7_QueryProcessorQueue31) RkaW+0Udspze TEIID30020 Processing exception for request RkaW+0Udspze.1 'TEII
D30151 Error building Source for context item.'. Originally TeiidProcessingException 'XML document structures must start and end within the same entity.' ErrorHandlerWrapper.java:201. Enable more detailed logging to see the entire stacktrace.`

**Comment by rareddy** [comment]
Don't convert to String, use blob response directly in your XMLTABLE construct?

**Comment by yapnel** [comment]
I'm doing something like this below. Do you think the 1st XMLTABLE is the culprit on the rs column that is used in the 2nd XMLTABLE?

`select
   g.*	
from 
( exec FRC_Source.invoke
 (
   binding=>'SOAP12',
   action=>'MESSAGE',
   request=>XMLPARSE(DOCUMENT XXX),
   endpoint=>'https://XXX/analytics-ws/saw.dll?SoapImpl=xmlViewService',
   stream=>'TRUE'
 )
) as f,
XMLTABLE 
( 
   XMLNAMESPACES('http://schemas.xmlsoap.org/soap/envelope' as soap,'urn://oracle.bi.webservices/v12' as sawsoap),
   '//sawsoap:rowset' PASSING f.result COLUMNS 
   rs string PATH 'text()' 
) as x,
XMLTABLE
(
   XMLNAMESPACES('urn:schemas-microsoft-com:xml-analysis:rowset' as xx),
   '/xx:rowset/xx:Row' PASSING XMLPARSE(DOCUMENT x.rs) COLUMNS 
   business_date string PATH 'xx:Column0/text()',
   "year" string PATH 'xx:Column1/text()',
   scenario string PATH 'xx:Column2/text()',
   org_unit_id string PATH 'xx:Column3/text()',
   "month" string PATH 'xx:Column4/text()',
   "org_unit_14" string PATH 'xx:Column5/text()',
   "b_line_6" string PATH 'xx:Column6/text()',
   "movement" string PATH 'xx:Column7/text()',
   "movement_ytd" string PATH 'xx:Column8/text()',
   "rep_chart_14" string PATH 'xx:Column9/text()',
   "rep_chart_id" string PATH 'xx:Column10/text()',
   "b_line_id" string PATH 'xx:Column11/text()'
)
as g
;`

**Comment by yapnel** [comment]
Change the rs string PATH 'text()' to rs clob PATH 'text()' has fixed the issue.

Thanks for the tip
