### ISSUE TITLE
Teiid K8s

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1245]
Hi

Is there intention of making Teiid runtime available on K8s too? I know the Redhat DI is only for Openshift. Just want to get a feel of the direction of travel.

Thanks

**Comment by rareddy** [comment]
Yes, absolutely. The S2I build is the main one, I am looking at options now but it might take little bit to completely make it K8 native.

**Comment by yapnel** [comment]
Fantastic. Is there a Jira for this requirement? I would like to stay inform. Thanks

**Comment by rareddy** [comment]
no single one, just watch the space, hopefully, I will put out a blog when we get there.

**Comment by rareddy** [comment]
you can log an issue in TEIIDTOOLS too.
