### ISSUE TITLE
Sharepoint List

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1247]
Hi

Do you have an example of how to connect to Sharepoint 2013 on-premise?

Thanks

**Comment by rareddy** [comment]
This is one hit I saw see if this is any helpful https://developer.jboss.org/thread/269374

There is no direct support yet, could be considered for a feature request

**Comment by yapnel** [comment]
Looks like sharepoint has Odata support. Is there an example of how to use Odata in Teiid please? Thanks

**Comment by rareddy** [comment]
Is that OData V2 or V4?

**Comment by yapnel** [comment]
I believe it is V4

**Comment by rareddy** [comment]
see this http://teiid.github.io/teiid-documents/master/content/reference/r_odata-v4-translator.html which gives a minimal example. We never tried with the Share Point, as we do not have an instance to test. Th
