### ISSUE TITLE
JSONTABLE Iterate Multiple Arrays

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1249]
Hi

Appreciate some technical guidance on pulling low, high and symbol values out from a JSON below. 

Below is my SQL and the low and high are returning an array values like [6462.60009765625,6231.10009765625,6088.5,5876.5,5696.47998046875]. How do i explode them into rows? THis is where i'm stucked and i can't figure out what to do. Thanks

SQL

> select
   x.*
from
(
   EXEC invokeHttp
   (
      action=>'GET',
      endpoint=>'https://query1.finance.yahoo.com/v8/finance/chart/%5EFTSE?range=5d&interval=1d',
      stream=>'FALSE'
   )
)
as f,
JSONTABLE(
    to_chars(f.result,'UTF-8',TRUE),
    '$' COLUMNS
    "symbol" string path '@.chart.result[0].meta.symbol',
    "high" string path '@.chart.result[0].indicators.quote[0].high',
    "low" string path '@.chart.result[0].indicators.quote[0].low'
) as x

JSON

> {
  "chart": {
    "result": [
      {
        "meta": {
          "currency": "GBP",
          "symbol": "^FTSE",
          "exchangeName": "FGI",
          "instrumentType": "INDEX",
          "firstTradeDate": 441962100,
          "regularMarketTime": 1584117966,
          "gmtoffset": 0,
          "timezone": "GMT",
          "exchangeTimezoneName": "Europe/London",
          "regularMarketPrice": 5366.11,
          "chartPreviousClose": 6462.6,
          "priceHint": 2,
          "currentTradingPeriod": {
            "pre": {
              "timezone": "GMT",
              "start": 1584083700,
              "end": 1584086400,
              "gmtoffset": 0
            },
            "regular": {
              "timezone": "GMT",
              "start": 1584086400,
              "end": 1584117000,
              "gmtoffset": 0
            },
            "post": {
              "timezone": "GMT",
              "start": 1584117000,
              "end": 1584119700,
              "gmtoffset": 0
            }
          },
          "dataGranularity": "1d",
          "range": "5d",
          "validRanges": [
            "1d",
            "5d",
            "1mo",
            "3mo",
            "6mo",
            "1y",
            "2y",
            "5y",
            "10y",
            "ytd",
            "max"
          ]
        },
        "timestamp": [
          1583740800,
          1583827200,
          1583913600,
          1584000000,
          1584117966
        ],
        "indicators": {
          "quote": [
            {
              "low": [
                5891.60009765625,
                5927.89990234375,
                5860.7998046875,
                5237.5,
                5237.47998046875
              ],
              "high": [
                6462.60009765625,
                6231.10009765625,
                6088.5,
                5876.5,
                5696.47998046875
              ],
              "close": [
                5965.7998046875,
                5960.2001953125,
                5876.5,
                5237.5,
                5366.10986328125
              ],
              "open": [
                6462.60009765625,
                5965.7998046875,
                5960.2001953125,
                5876.5,
                5237.47998046875
              ],
              "volume": [
                2098798700,
                1729622400,
                1507518600,
                2209275500,
                0
              ]
            }
          ],
          "adjclose": [
            {
              "adjclose": [
                5965.7998046875,
                5960.2001953125,
                5876.5,
                5237.5,
                5366.10986328125
              ]
            }
          ]
        }
      }
    ],
    "error": null
  }
}

**Comment by shawkins** [comment]
Unfortunately Json path lacks the expressiveness to do this directly.  You'd have to resort to a custom procedure, or use xmltable/xquery:

select
x.*
...
XMLTABLE('for $x at $pos in $a/response/chart/result[1]/indicators/quote[1]/low return <row> {$x/../../../meta/symbol}{$x}{$x/../high[$pos]}</row>'
  PASSING JSONTOXML('response', f.result) as a 
  COLUMNS symbol string, low decimal, high decimal
) AS x;

the context expression iterates over the low values to construct a row containing symbol/low/low, which is then easy to pluck the values out of.

It would be nice if there were some implicit index available of the current context item, but I'm not aware of anything like that.

**Comment by yapnel** [comment]
Thank you. 

Is there more documentation on the “for return <row>“ statement? That seems really powerful to do what i need.

**Comment by shawkins** [comment]
That is standard xquery: https://www.w3schools.com/xml/xquery_intro.asp

The actual implementation is saxon, which has a lot of support for additional functions especially: https://www.saxonica.com/html/documentation/functions/

**Comment by yapnel** [comment]
is there a way to convert epoch timestamp to datetime in Teiid? 

Thanks

**Comment by shawkins** [comment]
from_unixtime is probably what you are looking for: http://teiid.github.io/teiid-documents/master/content/reference/r_date-time-functions.html
