### ISSUE TITLE
invalid condition in .travis.yml

### ISSUE THREAD

**Issue by svenfuchs** [teiid/teiid#1250]
this condition https://github.com/teiid/teiid/blob/master/.travis.yml#L8:

```yaml
if: $TRAVIS_EVENT_TYPE != cron
```

is invalid and is being rejected. see the validation messages on e.g. https://travis-ci.org/github/teiid/teiid/builds/663577474/config

bash env vars are not available at this point, as these conditions are evaluated in our core system, outside of your build environment (VM)

instead you can use the condition:

```yaml
if: type != cron
```

see https://docs.travis-ci.com/user/conditions-v1 for more details on conditions.

**Comment by shawkins** [comment]
>  see the validation messages on

Are you referring to enabling: https://docs.travis-ci.com/user/build-config-validation

I don't really see validation messages produced otherwise on the config page nor the build log.

It does appear that the integration tests are running as expected.

> instead you can use the condition:

That's a simple enough change.
