### ISSUE TITLE
FORMATDATE Bug

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1252]
Hi

Inconsistent and wrong results for below

CURDATE is 2020-03-20

select FORMATDATE(CURDATE(),'mm-dd-yyyy'); -- Wrong
00-20-2020

select FORMATDATE(CURDATE(),'MM-dd-YYYY'); -- Correct
03-20-2020

select FORMATDATE(CURDATE(),'MM-DD-YYYY'); -- Wrong
03-80-2020

Looks like capital and lower capital yield different values.

Thanks

**Comment by shawkins** [comment]
This behavior comes straight from the JRE.  Our docs have a link to the date format java docs: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
