### ISSUE TITLE
Web Service Proxy Config

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1254]
Hi

Is there a way to configure proxy setting for CXF Web Service RA? I have to consume an external WS via the corporate proxy server that requires authentication. 

Kindly please advise

Thanks

**Comment by rareddy** [comment]
Look at teiid how we ask to set HTTPS at this page http://teiid.github.io/teiid-documents/master/content/admin/Web_Service_Data_Sources.html 

Then follow that, then supply the proxy similarly as defined here

https://cxf.apache.org/docs/client-http-transport-including-ssl-support.html#ClientHTTPTransport(includingSSLsupport)-ProxyAuthentication
