### ISSUE TITLE
Dynamic File Parsing

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1255]
Hi

I'm sourcing data from this https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv on a daily basis for Covid-19 reporting. This data is updated on a daily basis and new data is appended as "new column" at the end. I can consume the file without any issue but i have to change the view to include the new column everyday. 

Is there a way to dynamically add new column as part of the TEXTTABLE function and view? 

Thanks

**Comment by shawkins** [comment]
> Is there a way to dynamically add new column as part of the TEXTTABLE function and view?

They only way a view can handle that is by having array, xml, json, etc. columns that could vary.

I don't see a way to do this within texttable itself.  You'd have to write a procedure that uses dynamic sql to create the texttable you want for the given number of days.
