### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by aditya300899** [teiid/teiid#1259]
While building the project on terminal, i got a build success result but a few of dependencies weren't resolved. I took a pull from master branch btw. They were:
org.olap4j:olap4j-xmla:1.1.0
org.olap4j:olap4j:1.1.0
org.jboss.oreva:odata-core:1.0.0
org.jboss.oreva:common:1.0.0
How do i get these resolved?

**Comment by rareddy** [comment]
if you use `mvn install -s settings.xml` the `settings.xml` file has some extra repositories where these libraries can be found

**Comment by aditya300899** [comment]
I used the aforementioned command only. Tried one more time after you said. Didn't seem to work. Is there any other way?

**Comment by rareddy** [comment]
did you ever fix this issue and moved past this?

**Comment by aditya300899** [comment]
I build was fine. It was some problem with the ide, thus indexing couldn't have been done.

**Comment by rareddy** [comment]
as the cassandra work, see @shawkins did same for Salesforce here https://github.com/teiid/teiid/pull/1262 and I did same for FTP one here https://github.com/teiid/teiid/commit/da9b4a01f2405e67cbbc44345eb25e4ec48a089d

**Comment by aditya300899** [comment]
okay, lemme begin with this.

**Comment by aditya300899** [comment]
I could finally figure out why it was showing some of the dependencies not resolved on IntelliJ(they are shown with red underlines in the maven dialog on the right top corner) despite a fine build. I ignored this in the beginning but the thought of something was wrong made me try out different things. Just wanted to share just in case someone gets stuck with this same issue in future. 

If you are using non-default settings file for Maven please select it explicitly in IDE Maven settings: Settings (Preferences on macOS) | Build, Execution, Deployment | Build Tools | Maven | User settings file(add the path to settings.xml here). Now you can re-import all the dependencies and then restart the IDE by invalidating cache(this option comes under the file drop-down) and it's done.
