### ISSUE TITLE
REST POST

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1260]
Hi

I;ve got the REST endpoint below that works but when i try to consume within teiid i can't get it to work accordingly. Getting the below error. I suspect something is wrong with the param passing in POST. Kindly please advise . Thanks

REST Endpoint
> curl -X POST "http://localhost:5000/api/v1/newsnow" -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -d "timeline=3600&keywords=NHS"

Teiid SQL
>    EXEC invokeHttp
   (
      action=>'POST',
      endpoint=>'http://localhost:5000/api/v1/newsnow',
      request => 'timeline=3600&keywords=NHS',
      headers => 'accept: application/json',
      contentType => 'application/x-www-form-urlencoded'
   )

Error
> Caused by: Unexpected character (C) at position 0.
	at org.json.simple.parser.Yylex.yylex(Yylex.java:610)
	at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)

**Comment by rareddy** [comment]
Headers should be in the format
```
headers=>jsonObject('application/x-www-form-urlencoded' as "Content-Type", jsonObject('application/json') as "Accept")
```

**Comment by yapnel** [comment]
Getting this error

Invalid JSON for header.  The value must be a JSON Object containing list of primitive or primitive values

**Comment by yapnel** [comment]
Thank you
