### ISSUE TITLE
teiid importer.schemaPattern property didn't work

### ISSUE THREAD

**Issue by superchenwei** [teiid/teiid#1263]
```
<vdb name="my_vdb" version="1">
  <model name="my_vdb" visible="true">
    <property name="importer.schemaPattern" value="my_schema"/>
    <source connection-jndi-name="java:/mysql234" name="mysql234" translator-name="mysql"/>
  </model>
</vdb>
```
all schema were loaded in vdb,importer.schemaPattern not work
please helping fix this,thank you

**Comment by shawkins** [comment]
There's not much to go by here.  The vdb snippet shows the correct setting.  What schema are you actually getting from the source?  Keep in mind that the pattern is like match string, so the meta characters % and _ can be problematic.  Also the support for the schemaPattern is coming from the driver's implementation of DatabaseMetaData - what driver are you using?

**Comment by shawkins** [comment]
Moved to stackoverflow

**Comment by superchenwei** [comment]
I'm using mysql-connector-java-8.0.16.jar

**Comment by shawkins** [comment]
Please follow up on the stackoverflow post so that we can avoid cross-posting.
