### ISSUE TITLE
REST SSL Verification

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1264]
in a REST call, is it possible to switch of SSL verification?

**Comment by shawkins** [comment]
For rest calls using Teiid wildfly with cxf, you would need to use the spring configuration option to set disableCNCheck - similar to https://stackoverflow.com/questions/21120264/https-url-hostname-not-matching-common-name-cn-despite-setting-disablecncheck

**Comment by yapnel** [comment]
What is the spring configuration option and how to set the variable in wildfly? I am not familiar with it, kindly please advise. Thanks

**Comment by rareddy** [comment]
It is the cxf properties file

**Comment by shawkins** [comment]
Ramesh are you referring to a WildFly global config file?

The ws resource adapters have a configFile option - http://teiid.github.io/teiid-documents/master/content/admin/Web_Service_Data_Sources.html

That doc page shows several sample config files for doing common things, like enabling logging.

**Comment by rareddy** [comment]
I meant the same configFile you mentioned
