### ISSUE TITLE
REST Escape Single Quote

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1274]
Hi
The single quote wrapping the value by guid is causing the invokeHTTP to fail. I need the single quote there for the REST query to work. How do i escape it? Tried two single quotes and backslash  but neither worked. Please advise

> Lists(guid'0d4af435-382f-4371-ac5a-1a0440400db8')

> 	select
       --x.*
       to_chars(f.result,'UTF-8',TRUE),
	from
	(
	   EXEC invokeHttp
	   (
	      action=>'POST',
	      endpoint=>'https://XXX/api/v1/splists',
	      request => 'uri=https://XXX/teams/0000673/Covid-19/_api/Web/Lists(guid'0d4af435-382f-4371-ac5a-1a0440400db8')/Items?$select=Title,Action,Next_x0020_Steps,Owner,By_x0020_when_x003f_,Modified,Progress',
	      headers => jsonObject('application/x-www-form-urlencoded' as "Content-Type",'application/json' as "Accept")
	   )
	)
	as f

**Comment by shawkins** [comment]
You just need an extra single quote to escape a single quote in a string literal.

'I''m home'

When you say that did not work, what was the issue?

**Comment by yapnel** [comment]
tried putting an extra single quote but getting the error below

> Error: Remote org.teiid.api.exception.query.QueryParserException: TEIID31100 Parsing error: Encountered "TRUE), [*]from[*] ( EXEC" at line 3, column 9.
Was expecting: "char" | "date" | "time" | "timestamp" | "cast" | "convert" | "any" | "array" | "array_agg" | "case" ...
SQLState:  50000
ErrorCode: 0

**Comment by yapnel** [comment]
My apologies. My mistake there was a syntax error in the query. It is working now with the additional single quote. Thanks
