### ISSUE TITLE
Empty Coordinate Pairs for geometry values

### ISSUE THREAD

**Issue by sebastian-r-schmidt** [teiid/teiid#1318]
I'm using teiid v13.1 in wildfly v17.0.1 bundled in the current docker image jboss/teiid:latest and I applied the patch necessary from github Issue teiid-1314 (unresolved library dependency for JTS).

Exposing geometry types via Odata4 is working only for a small amount of geospatial data types. Except for geo_view_point, all entities in this example return empty coordinate pairs on the location attribute for multipoint, (multi)linestring and (multi)polygon data types. e.g. http://localhost:8080/odata4/gistest/foo/geo_view_multipolygon(1)/location/$value?$format=json

Parsing of WKT takes place, as there are corresponding errors when the EWKT text ist invalid. The examples for EWKT are taken from wikipedia: https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

Anything which needs to be set up additionally?

Defined VDB:

```
CREATE view geo_view_point 
(id integer primary key,
   location geometry options 
   ("teiid_spatial:coord_dimension" 2, 
    "teiid_spatial:srid" 4326,
    "teiid_spatial:type" 'point')
)
AS select 1, ST_POINT(1.0, 2.0);


CREATE view geo_view_multipoint 
(id integer primary key,
   location geometry options 
   ("teiid_spatial:coord_dimension" 2, 
    "teiid_spatial:srid" 4326,
    "teiid_spatial:type" 'multipoint')
)
AS select 1, ST_GEOMfromEWKT('SRID=4326;MULTIPOINT ((10 40), (40 30), (20 20), (30 10))');

CREATE view geo_view_linestring
(id integer primary key,
   location geometry options 
   ("teiid_spatial:coord_dimension" 2, 
    "teiid_spatial:srid" 4326,
    "teiid_spatial:type" 'linestring')
)
as select 1, ST_GeomFromEWKT('SRID=4326;LINESTRING(10 40,12 45,12 48)');

CREATE view geo_view_multilinestring
(id integer primary key,
   location geometry options 
   ("teiid_spatial:coord_dimension" 2, 
    "teiid_spatial:srid" 4326,
    "teiid_spatial:type" 'multilinestring')
)
as select 1, ST_GeomFromEWKT('SRID=4326;MULTILINESTRING ((10 10, 20 20, 10 40),
(40 40, 30 30, 40 20, 30 10))');


CREATE view geo_view_polygon 
(id integer primary key,
   location geometry options 
   ("teiid_spatial:coord_dimension" 2, 
    "teiid_spatial:srid" 4326,
    "teiid_spatial:type" 'polygon')
)
AS select 1, ST_GeomFromEWKT('SRID=4326;POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))');


CREATE view geo_view_multipolygon 
(id integer primary key,
   location geometry options 
   ("teiid_spatial:coord_dimension" 2, 
    "teiid_spatial:srid" 4326,
    "teiid_spatial:type" 'multipolygon')
)
AS select 1, ST_GeomFromEWKT('SRID=4326;MULTIPOLYGON (((30 20, 45 40, 10 40, 30 20)),
((15 5, 40 10, 10 20, 5 10, 15 5)))');
```

**Comment by shawkins** [comment]
Did you apply https://issues.redhat.com/browse/TEIID-5997 - that addresses the issue with the coordinates.

**Comment by shawkins** [comment]
I'll release a 14.0.1 that contains both of these fixes today.

**Comment by sebastian-r-schmidt** [comment]
Ok, I thought that TEIID-5997 would only affect polygons with holes. Apparently this was not the case. Fetching the snapshot jar form oss sonatype fixes the issue. Looking forward to a 14.0.1 release.
