### ISSUE TITLE
Migration Guide

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1324]
Hi

Is there migration guide from 13 to 15 please?

Thanks

**Comment by shawkins** [comment]
I've just been doing single version guides, so there is one from 13 to 14 and 14 to 15.  Unfortunately I needed to correct how those were getting published as I had at one point started down the path of creating a merged guide as there's not a lot to note in the 14/15 migrations from Teiid 13.  Regardless they are there now: http://teiid.github.io/teiid-documents/master/content/admin/Administrators_Guide.html
