### ISSUE TITLE
Custom JDBC Port

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1328]
Wondering is it possible to change the JDBC port of 31000 to 8080? And will it work?

Thanks

**Comment by shawkins** [comment]
Any available port will work for Teiid JDBC traffic.  So if running in the container, you'll have to first reassign http traffic.  Or are you asking if there is an option to access Teiid JDBC over http?

**Comment by yapnel** [comment]
Should have been clearer with my question. Yes, JDBC over http(s) is what I am after. 

I know we can connect to snowflake over http(s) from within corporate network and wondering it can be done the same for teiid. 

Lets say we are using Openshift PaaS and want to connect squirrel using JDBC, this will entail in changing the corporate firewall rules etc ... whereas over http(s) it will just work.

Thanks

**Comment by shawkins** [comment]
> Yes, JDBC over http(s) is what I am after.

There is no longer a way to do that directly.  Given odata and rest access the limited support that was in Teiid for a http client/server protocol was removed a long time ago.  If your traffic has to specifically be jdbc over http rather than one of our outer interfaces or anything over tls/tcp that would require some kind of alternative transport logic.

**Comment by yapnel** [comment]
Just out of curiosity, how did Teiid implement JDBC over http? Are there are docs or links I can read about?

Thanks

**Comment by shawkins** [comment]
It was a soap endpoint: https://github.com/teiid/teiid/tree/6.0.x/soap/src/main that was written to interact with the engine in a direct manner (not over top of another transport).  It was removed for Teiid 7.x, which was quite a long time ago.

**Comment by yapnel** [comment]
Without digging into the code, I assume the SQL is inside the soap payload for execution in the engine and the resultset is return as XML and translated by the driver to tabular format? Will the performance be not on par with JDBC over TCP?

**Comment by shawkins** [comment]
> I assume the SQL is inside the soap payload for execution in the engine and the resultset is return as XML and translated by the driver to tabular format?

Effectively yes.

> Will the performance be not on par with JDBC over TCP?

It was not on par no.  There's a lot of extra latency from the soap message / xml processing.  It's similar to the overhead seen when fetching xml results over OData.  If you don't mind the overhead there are vendors that provide a jdbc to odata bridge - which could also be developed by using Teiid client with Teiid embedded that runs an odata translator pointed to the remote odata endpoint.  You of course also loose things like local transactions in that scenario.

A transport like this being developed today would start with REST or websockets, not SOAP.
