### ISSUE TITLE
The definition for procedure has the wrong type for column 1.  Expected clob, but was json

### ISSUE THREAD

**Issue by halace** [teiid/teiid#1334]
I am using docker container  based out of the image 
 jboss/wildfly:17.0.1.Final 
using the runtime : teiid-wildfly-12.3.1-dist.zip

The VDB is REST enabled and please see the properties set on the procedure

![image](https://user-images.githubusercontent.com/72036424/94478944-febb9200-01a1-11eb-8912-1c4706214b6b.png)

Here is the final select in the procedure
SELECT JSONOBJECT(JSONARRAY_AGG(JSONOBJECT(Integration_View.PROVIDER.DB_CODE, Integration_View.PROVIDER.COUNTRY, I))) AS json_out FROM Integration_View.PROVIDER

Teiid designer compiles the procedure and no errors , but while deploying the VDB, I see this error 

 use WITHOUT RETURN to indicate the statement should not be returned - The definition for Service_View.getFacilityJson has the wrong type for column 1.  Expected clob, but was json.

Please help as this code works well in JDV 6.4.7 and not in community version

**Comment by shawkins** [comment]
json was refined to be a full type with https://issues.redhat.com/browse/TEIID-5499 - see the first comment about the potential for a breaking change.  The version of Teiid Designer you are using may not be aware of the json type and thus allowing the vdb to be created without an error.  If it won't allow to change the return type of the procedure to json, then the workaround to continue using designer is to add a cast to clob.

**Comment by halace** [comment]
Thanks for the quick response.  Please let me know the teiid designer version I should use. Or how I can cast to clob? Right now I dont see an option for json in Teiid Designer 11.2.1 Thank you again

**Comment by shawkins** [comment]
There is no later release of Teiid Designer to use unfortunately.

To cast as clob: SELECT cast(JSONOBJECT ... as clob) AS json_out ...

**Comment by halace** [comment]
Thannks, this worked
