### ISSUE TITLE
Code Formatter

### ISSUE THREAD

**Issue by treiboll** [teiid/teiid#1341]
Hi, 

exists any code formatter (template) for VDB ddl files for e.g. Intellij (or another IDE)?

Our VDB file counts about 1600 lines and we use very often the "options" syntax. It is not possible to maintaine the formatting by hand and the different formatter for different SQL dialects in Intellij do not work. 

Regards,
Fabian

**Comment by shawkins** [comment]
I'm not aware of an existing extension for that.  There was work started on a language server for vscode: https://github.com/teiid/teiid-language-server - that probably could be adapted.

**Comment by treiboll** [comment]
ok, I will check that

Thanks for the quick reply
