### ISSUE TITLE
Clarification to OData geo functions in $filter queries

### ISSUE THREAD

**Issue by fkn-iteratec** [teiid/teiid#1343]
Hi, 

I have question to OData geo functions in $filter queries. My project is on:

- Teiid-Spring-Boot 1.7.1
- Teiid- 16.0

Example for an OData query snipped:
../odata/myservice/myentity?$filter=geo.intersects(myentity_geo_property, geometry'POINT(691675.07 5334759.05)') eq true

Because of my use case, I tried to switch the sequence of the parameters of geo.intersects() and got errors. 'myentity_geo_property' is in my case not a POINT and the OData function signature defines it: geo.intersects(Edm.GeometryPoint,Edm.GeometryPolygon).

So my question: Must be the first parameter of geo.intersects always the property of the entity itself? If so: Is this intended or a bug? 

Regards,
Fabian

**Comment by shawkins** [comment]
The odata logic in org.apache.olingo.server.core.uri.parser.ExpressionParser is expecting to see point, then polygon - and that does seem to be baked into the specification.   So as long as you can pass a point, then a polygon everything should work.
