### ISSUE TITLE
Column names with spaces error

### ISSUE THREAD

**Issue by dbarasti** [teiid/teiid#1351]
Hello there, I have a valid VDB definition where the source database column names containing spaces, are enclosed in double quotes. The deployment is successful, but when I query the data using a sql client (SQuirreL in my case) I get the following error:

```
Error: TEIID30504 Remote org.teiid.core.TeiidProcessingException: TEIID30504 local: 156 TEIID11008:TEIID11004 Error executing statement(s): [Prepared Values: [] SQL: SELECT g_0.Numero_viaggio AS c_0, g_0.Numero nave AS c_1, g_0.Data arrivo AS c_2, g_0.Orario arrivo AS c_3, g_0.Data Partenza AS c_4, g_0.Orario Partenza AS c_5 FROM VIAGGI g_0 ORDER BY @@version OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY]
```
The snippet of the VDB definition is the following:

```
CREATE FOREIGN TABLE VIAGGI
(
        Numero_viaggio string(50) PRIMARY KEY,
        "Numero nave" string(50),
        "Data arrivo" string(50),
        "Orario arrivo" string(50),
        "Data Partenza" string(50),
        "Orario Partenza" string(50)
);
```
Removing the columns containing spaces from the VDB definition makes it work, so I'm pretty sure the error has to do with the spaces.

Thank you in advance for the help

**Comment by shawkins** [comment]
Most of translator logic expects you to provide a nameInSource property when the source column name is different than the table name (when using an importer, it takes care of that for you).  

 "Numero nave" string(50) OPTIONS (NAMEINSOURCE '"Numero nave"')

**Comment by dbarasti** [comment]
Thank you for the quick answer! The problem here is not that the column names differ, I just have in my source database columns with spaces, and to represent them in the vdb definition I used double quotes (cause I thought it would be the correct way to represent names with spaces). But then, when I query the vdb I get the error reported above.

**Comment by shawkins** [comment]
> However, the problem here is not that the column names differ

Yes they do.  If you have the identifier name as "Numero nave", the actual name is still just the string Numero nave - the quoting is simply allowing the identifier to contain special characters.  The quotes are not carried forward to the source query.

**Comment by dbarasti** [comment]
Gotcha! It's working now. Thank you for your work!
