### ISSUE TITLE
Change field type using scalar functions

### ISSUE THREAD

**Issue by dbarasti** [teiid/teiid#1355]
Hello there,
I am trying to parse a `string` column in order to change its type into a `date`, while defining the foreign table in the vdb file. My `-vdb.xml` file contains the following:

```
CREATE FOREIGN TABLE Trips
(
        Trip_number string(50) PRIMARY KEY,
        Ship_number string(50) OPTIONS (NAMEINSOURCE '"Ship number"'),
        Arrival_date string(50) OPTIONS (NAMEINSOURCE '"Arrival date"'),
        Arrival_time time OPTIONS (NAMEINSOURCE '"Arrival time"'),
        Departure_date string(50) OPTIONS (NAMEINSOURCE '"Departure date"'),
        Departure_time time OPTIONS (NAMEINSOURCE '"Departure time"')
);
```

And I'd like to change the Arrival_date and Departure_date columns so that they are parsed into `date`s.

I tried the following, but it fails compiling:

```
CREATE FOREIGN TABLE Trips
(
        ...
        parseDate(Arrival_date, 'dd"/"MM"/"yyyy') date OPTIONS (NAMEINSOURCE '"Arrival date"'),
        ...
        parseDate(Departure_date, 'dd"/"MM"/"yyyy') date OPTIONS (NAMEINSOURCE '"Departure date"'),
        ...
);

```

Can you help me figure out if there is a proper way to do that directly in the foreign table definition? I am open to other solutions.

Thank you as always

**Comment by rareddy** [comment]
You can not use parseDate it in the `FOREIGN TABLE`. The foreign table represents the exact replica of the source. You can try defining the `Arrival_date` as `date` directly, then it will be looking at the database date format as expected by `java.sql` package expectations. Depending upon database and format this might work. Alternatively, you can always create `VIEW` with transformation using the `ParseDate` with a custom date format.

**Comment by dbarasti** [comment]
Thank you for the help @rareddy. I solved the problem with the virtual table solution.

**Comment by dbarasti** [comment]
@rareddy I now bump into another problem: Odata only maps tables with a primary key defined, so my newly defined view isn't available for query using Odata. Do you have a suggestion on that matter?

**Comment by rareddy** [comment]
You can do like `CREATE VIEW trips ( row_id integer primary key, arrivaldate xxxx, depaturedate xxx, trip_number xxx)
 AS select row_number() over (order by trip_number), parsedate(...), parsedate(...), ... from ...` that gives you row_id as PK but ephemermal, so do not do base any queries based on its value as it can change query to query.

**Comment by dbarasti** [comment]
That's great. Thank you again for the help!
