### ISSUE TITLE
HTML pages on Teiid site are broken links.

### ISSUE THREAD

**Issue by jayunit100** [teiid/teiid#693]
Seems like `http://teiid.jboss.org/downloads/` is the right place to go, but there are many links to things like `http://teiid.jboss.org/download.html` and so on.

Lets update all the links to not point to hardcoded html endpoints.

**Comment by shawkins** [comment]
I don't see a single reference on the community site to download.html, can you be more specific about where you are seeing this?

**Comment by shawkins** [comment]
There was a page link to the designer download similar to what you are describing.  That along with some others have been addressed.  But if there is something that you are seeing elsewhere, just let us know.

**Comment by jayunit100** [comment]
iirc i saw it a couple of places ,  it was in the wiki site ... https://developer.jboss.org/wiki/Teiid70InstallationGuide but i guess that stuff is obsolete now.....  maybe it should be deleted.

**Comment by shawkins** [comment]
Yes, that is quite old at this point - we'll at least add a deprecation notice, if not delete completely.

**Comment by shawkins** [comment]
Thanks Jay. Took a pass through the articles and added out-of-date warnings as needed.
