### ISSUE TITLE
Bug with comparing date on a datetime field

### ISSUE THREAD

**Issue by sdherr** [teiid/teiid#700]
I believe there is a bug with comparing <= on just the date portion of a datetime field:

select * from Table where DatetimeColumn::date > '2016-02-28' and DatetimeColumn::date <= '2016-02-29'
[]

select * from Table where DatetimeColumn > '2016-02-28T23:59:59' and DatetimeColumn <= '2016-02-29T23:59:59'
[result,
result,
result,
result]

Can someone who knows the appropriate place to look in the code take a look please? I've only noticed the problem on the '<=' operator, '>=' seems to work correctly.

**Comment by sdherr** [comment]
Sorry, replace the 'T' with a ' ' (space) in the above datetime strings. Although I would expect both to work...

**Comment by shawkins** [comment]
> Although I would expect both to work...

Teiid recognizes the JDBC standard timestamp string, not the iso format.

> I believe there is a bug with comparing <= on just the date portion of a datetime field:

There are a lot of details missing here such as what version you are using, what client you are using (the initial sql implies a pg client), and the query plan would be helpful - to determine if the comparisons are being pushed.

**Comment by shawkins** [comment]
Closing as there have been no updates.  Please open a JIRA with more information - https://issues.jboss.org/projects/TEIID
