### ISSUE TITLE
Unable to get managed connection for null

### ISSUE THREAD

**Issue by get2parag** [teiid/teiid#825]
I could be late here but thanks for moving to GITHUB, makes life simpler for rest of the developers to contact the core team.

Now, the reason I'm here is we are using TEIID embedded server to join multiple datasources in our project and we have been facing intermittent issues for connectivity of TEIID server with one of the datasource which is oracle. The other datasource postgres works fine, however both are initialized(pool and connectionfactory) using the same way. Also both these data sources are referenced inside the same VDB. The trimmed version of exception trace is :- 
`Caused by: org.teiid.core.TeiidProcessingException: TEIID30504 oracle: TEIID11009 java.sql.SQLException: javax.resource.ResourceException: IJ000453: Unable to get managed connection for null
        at org.teiid.dqp.internal.process.DataTierTupleSource.exceptionOccurred(DataTierTupleSource.java:385)
        at org.teiid.dqp.internal.process.DataTierTupleSource.nextTuple(DataTierTupleSource.java:154)
        at org.teiid.query.processor.relational.AccessNode.nextBatchDirect(AccessNode.java:374)
        at org.teiid.query.processor.relational.RelationalNode.nextBatch(RelationalNode.java:282)
        at org.teiid.query.processor.BatchIterator.finalRow(BatchIterator.java:69)
        at org.teiid.common.buffer.AbstractTupleSource.getCurrentTuple(AbstractTupleSource.java:70)
        at org.teiid.query.processor.BatchIterator.getCurrentTuple(BatchIterator.java:84)
`

It's causing us loss of sleepless nights as the current code in production starts failing after few days due to above exception and only way to recover is re-initialize the pool or restart the server (a spring boot app). Any clues to resolve this will be greatly appreciated.

Configurations:-
<teiid.version>8.12.2</teiid.version>
<ironjacamar.version>1.0.30.Final-redhat-1</ironjacamar.version>
<narayana.version>5.2.13.Final</narayana.version>
<oracle-driver.version>12.1.0.2.0</oracle-driver.version>

Connection factory and pool is initialized by the following way :- 
`

		LocalManagedConnectionFactory mcf = new LocalManagedConnectionFactory();
		mcf.setDriverClass(driverClass);
		mcf.setConnectionURL(connURL);
		mcf.setUserName(user);
		mcf.setPassword(password);
		mcf.setCheckValidConnectionSQL(validConnSql);
		mcf.setValidateOnMatch(true);

		mcf.setValidConnectionCheckerClassName(getValidConnCheckerClassName(driverClass));
		PoolConfiguration pc = new PoolConfiguration();
		pc.setPrefill(false);
		pc.setUseFastFail(failFast);
		pc.setBackgroundValidation(true);
		pc.setMaxSize(maxSize);
		pc.setMinSize(minSize);
		pc.setStrictMin(false);

		PoolBySubject pool = new PoolBySubject(mcf, pc, false);
		NoTxConnectionManagerImpl cm = new NoTxConnectionManagerImpl();
		pool.setConnectionListenerFactory(cm);
		cm.setPool(pool);

		return mcf.createConnectionFactory(cm);
`
For obtaining a JDBC connection from teiid server, teiid driver is used and VDB name is passed.
Let me know if any other information is required to debug this issue.

**Comment by shawkins** [comment]
It is best to use the jboss.org forums and issue tracking as those are our primary systems. Other users with similar issues: https://developer.jboss.org/thread/211940
show the underlying cause as an Oracle issue in obtaining a connection in a specific scenario that is using too many connections.  You'll need to check the root exception and verify that you're not consuming more connections from oracle than what is allowed.

**Comment by get2parag** [comment]
sure, i'll raise it jboss forums thanks.

However would you have any comment on how the pool is created or anyways to optimize it or what is the prescribed practice here w.r.t TEIID.

**Comment by shawkins** [comment]
It's certainly a valid pool configuration, but I'm afraid there's no way to really guess at an optimization as we don't know your usage pattern or even what is the root cause of your issue.
