### ISSUE TITLE
Swagger translator wrong handling of response Content-Type with charset parameter

### ISSUE THREAD

**Issue by leonidr** [teiid/teiid#858]
https://github.com/teiid/teiid/blob/master/connectors/swagger/translator-swagger/src/main/java/org/teiid/translator/swagger/SwaggerProcedureExecution.java#L282

This code will fail with Content-Type using charset parameter : 
https://www.w3.org/International/articles/http-charset/index#charset

like
Content-Type: application/json; charset=utf-8

**Comment by rareddy** [comment]
Can you open a JIRA at https://issues.jboss.org/projects/TEIID ?

Also if you can provide a patch that would be great! Thanks

**Comment by shawkins** [comment]
Moved to https://issues.jboss.org/browse/TEIID-4697
