### ISSUE TITLE
EmbeddedServer expects a VDB file and not just a URL

### ISSUE THREAD

**Issue by NKame** [teiid/teiid#859]
I run an EmbeddedServer with this code:
```
		server.deployVDBZip(this.getClass()
				.getResource("/vdb/" + VDB + ".vdb"));
```
as long as the application is not packaged, it's working fine. When the resources are inside a Jar (Spring Boot, not a straight Jar file):
```
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:418) ~[na:1.8.0_111]
        at org.teiid.query.metadata.PureZipFileSystem.mount(PureZipFileSystem.java:72) ~[teiid-engine-9.1.1.jar!/:9.1.1]
        at org.teiid.runtime.EmbeddedServer.deployVDBZip(EmbeddedServer.java:715) ~[teiid-runtime-9.1.1.jar!/:9.1.1]
```

The problem is in PureZipFileSystem (same in master):
```
    public static VirtualFile mount(URL url) throws IOException, URISyntaxException {
		//we treat each zip as unique if it's possible that it 
		String fileName = "teiid-vdb-" + url.toExternalForm(); //$NON-NLS-1$
		VirtualFile root = VFS.getChild(fileName);
		File f = new File(url.toURI());
```
The parameter is a URL, but it's handled as if it was a "file:" URL, which is not the case here.

**Comment by rareddy** [comment]
Why not use a XML based VDB file instead? If the aim is to use the Designer, it has option to export the VDB as XML file. The .vdb support is more or less going deprecated. We have not vetted the SpringBoot based deployment yet.

Another alternative is to use deployVDB(InputStream) method, where you can access/load the VDB using SpringBoot classloader and avoid the builtin URL resolution.

**Comment by NKame** [comment]
Well, the situation is a bit confusing right now from a Teiid-beginner point of view :-) Teiid Designer tends to work with XMI and generate VDB Zip, and Teiid can ingest the Zip but not the XMIs, and it's not quite clear which way to go to benefit from the designer and have easy embedding while not having too many manual tasks. Right now we are on the verge on not using VDBs at all but directly the DDLs, but that still requires to export them one by one in Teiid Designer.

**Comment by rareddy** [comment]
XMI is way tooling stores the model usng EMF, but for runtime it creates a binary file in .INDEX files for consumption by the Teiid runtime. All this is being deprecated in next version to support XML/DDL based VDBs. So, my recommendation is move away from .VDB type going forward.

As I mentioned before, you can use the Designer, but export it as XML/DDL file at the end and use that. Or you do not care to use Designer or you have usecase where you need to add/remove sources ad-hoc to provide some dynamic capabilities then you can hand code the VDB (this is just plain text file) or even programatically drive the VDB design. So it depends on what you want to do. Let me know if that is not clear.

**Comment by NKame** [comment]
Yep, I've read that part of the code for the XMI / INDEX stuff :) In our context, we would like to go on using Teiid Designer for all the visualization / graphic parts. We know our sources beforehand, the only thing we'd need is a kind of "export DDL for all XMI in the project" to ease the flow: that's what we have with VDB: one click and we know that everything is up to date. We'll remove the usage of Zip files, let's close this ticket.
